### PR TITLE
Schema tests

### PR DESCRIPTION
**Pull request by simzzz**

### CODE REVIEW

**Comment by simzzz** [comment]
> Pull master first
Already did, though github UI shows it under the changes from 12th of September.
https://github.com/AdExNetwork/adex-models/pull/10/commits/19009e24ea7320fb579096f874f53fad2d0d65ff

**Comment by IvoPaunov** [comment]
Ok, 
* can you make the test data better e.g one valid object and then spread it and change only some props for the different cases.
* add test for campaigns
* generate the long string with function

**Comment by IvoPaunov** [comment]
use `Joi.validate(....).error.message, 'MSG_TEXT'` instead `"Error: MSG_TEXT"`

**Comment by rori4** [comment]
Also it is a good idea to extract the schema error messages into a separate file and use those constant to validate.
For example: 
```authToken: Joi.string().required().error(new Error('AUTH_TOKEN_ERR')),```

```AUTH_TOKEN_ERR``` should be in a constant and then used in the test ```Joi.validate(....).error.message, 'AUTH_TOKEN_ERR '```

**Pull request merged**
